refactor: rename constrain to scope
cycle/orm pull request #185
Opened 2021-05-18 17:55 UTC by hustlahusky

Closes #65

- Replace "constrain" with "scope" all over the code base
- Add BC aliases with deprecation replacement suggestion (need to ignore cs warning on alias files)

2021-05-18 18:33 UTC, wolfy-j commented
I  believe it's best to add for v2.

2021-05-20 07:46 UTC, hustlahusky commented
Ok. I can rebase this changes to 2.0 branch later. Should I drop BC aliases then?

2021-05-20 10:01 UTC, wolfy-j commented
Yes, we can BC them for v2.

2021-05-20 10:33 UTC, roxblnfk commented
I think this PR is ok for v1.x
User also can use the old constant that marked as deprecated. In v2 we can break BC and remove the deprecated constant

2021-05-20 10:46 UTC, wolfy-j commented
You can approve it then :)

2021-05-20 12:39 UTC, roxblnfk commented
> You can approve it then :)

👍
But too lot changes :) i will review this later

2021-06-05 21:37 UTC, wolfy-j commented
Ping @roxblnfk

2021-06-05 22:14 UTC, roxblnfk commented
If @hustlahusky  will do not force push changes with overwriting previous commits then i ready to review ;)

2021-06-05 22:15 UTC, roxblnfk commented
Also not all tests passed

2021-06-06 07:43 UTC, hustlahusky commented
> If @hustlahusky will do not force push changes with overwriting previous commits then i ready to review ;)

Yeah. I finished with changes for now :)

> Also not all tests passed

Tests are ok. Only check failed is code style caused by warnings in BC aliases files. It needs to be ignored, but I don't know how to do that

2021-06-07 17:10 UTC, roxblnfk requested changes
I think we need to add tests that check:
- old methods are work
- old interfaces (classes) are work
- old options and constants work too

2021-06-07 17:16 UTC, roxblnfk commented
> Tests are ok. Only check failed is code style caused by warnings in BC aliases files. It needs to be ignored, but I don't know how to do that

I think you can move deprecated stubs in the `resources/stubs` directory like [here](https://github.com/cycle/annotated/tree/master/resources/stubs)

2021-06-08 06:42 UTC, hustlahusky commented on src/Select/Scope/QueryScope.php
> +namespace Cycle\ORM\Select\Scope;
I have plans to add some more scope options in future for #24, that can be helpful for implementing extra lazy collection behavior like in doctrine

2021-06-08 06:46 UTC, hustlahusky commented on src/Select/JoinableLoader.php
> +        $options = $this->prepareOptions($options);
`prepareOptions` returns modified options array. Without calling this here, options can have `constain` key instead of `scope`

2021-06-08 06:46 UTC, hustlahusky commented on src/Select/JoinableLoader.php
> -            $loader->setConstrain($this->getSource()->getConstrain());
Yes

2021-06-08 08:05 UTC, roxblnfk commented on src/Select/JoinableLoader.php
> +        $options = $this->prepareOptions($options);
But the `$options` variable is not used after `parent::withContext`

2021-06-08 08:46 UTC, hustlahusky commented on src/Select/JoinableLoader.php
> +        $options = $this->prepareOptions($options);
No, it is used here https://github.com/cycle/orm/blob/7e0f3a9b5a5472f7b4a17cdb5efc73524e1d39b3/src/Select/JoinableLoader.php#L125

2021-06-21 15:44 UTC, hustlahusky commented
Split small improvements that can be merged to v1 in #191
I will open new PR to v2 with other changes later

2021-06-21 15:44 UTC, closed without merging

2021-06-21 16:09 UTC, roxblnfk commented
> I will open new PR to v2 with other changes later

Be careful, because now branch 2.0 is actively changing.